/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login_Form;

import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.Scanner;

import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class Register extends javax.swing.JFrame {
    Music music = new Music();

    String soundEffect = "MenuSoundEffect.wav";

    /**
     * Creates new form Register
     */
    public Register() {
        this.setTitle("Register");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register_Button = new javax.swing.JButton();
        Username_Field = new javax.swing.JTextField();
        Password_Field = new javax.swing.JPasswordField();
        Name_Field = new javax.swing.JTextField();
        Name_Icon = new javax.swing.JLabel();
        Password_Icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserName_Icon = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        Login_Background_Video = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register_Button.setText("Register");
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 90, 20));

        Username_Field.setText("username");
        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 126, -1));

        Password_Field.setText("jPasswordField1");
        getContentPane().add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 126, -1));

        Name_Field.setText("name");
        getContentPane().add(Name_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 126, -1));

        Name_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Form/icons8-user-16.png"))); // NOI18N
        getContentPane().add(Name_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 30, 20));

        Password_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Form/icons8-password-24 (1).png"))); // NOI18N
        getContentPane().add(Password_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 30, 20));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Multiverse Of Chess");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 360, 70));

        UserName_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Form/icons8-user-16.png"))); // NOI18N
        getContentPane().add(UserName_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 30, 20));

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 90, 20));

        Login_Background_Video.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Form/The_Chess_Game_l_Cinematic_Chess_B_Roll_l_Edelkrone_AdobeExpress (1).gif"))); // NOI18N
        getContentPane().add(Login_Background_Video, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
        String name = Name_Field.getText();
        String username = Username_Field.getText();
        String password = Password_Field.getText();

        String savedUserName;
        try
        {
            File AccountsData = new File("AccountsData.txt");
            Scanner scan = new Scanner (AccountsData);
            scan.useDelimiter("[,\n]");
            boolean check =false;

            while(scan.hasNext()){
                scan.next();
                savedUserName = scan.next();
                scan.next();
                if(username.equals(savedUserName.trim())){
                    check = true;
                    break;
                }
            }
            if(check == true){
                JOptionPane.showMessageDialog(null,"UserName is not valid");
                Username_Field.setText("");
            }
            else{
                try {
                    FileOutputStream AccountsData2 = new FileOutputStream("AccountsData.txt", true);
                    PrintWriter printer = new PrintWriter(AccountsData2);

                    printer.println(name + "," + username + "," + password);
                    JOptionPane.showMessageDialog(null, "registered done");
                    printer.close();

                    this.dispose();
                    Login login = new Login();
                    login.setVisible(true);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"an error occured"+e);
                }
                CreateHistoryFile();
                CreateContinueFile();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"an error occured"+e);
        }
    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        music.PlaySoundEffect(soundEffect);
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        music.PlaySoundEffect(soundEffect);
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    
   private void CreateHistoryFile(){
       String HistoryFileName = Username_Field.getText();
       CreateHistory History = new CreateHistory(HistoryFileName);
   }
   
       private void CreateContinueFile() {
       String ContnueFileName = Username_Field.getText();
       CreateContinue ContinueFile = new CreateContinue(ContnueFileName);    
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel Login_Background_Video;
    private javax.swing.JTextField Name_Field;
    private javax.swing.JLabel Name_Icon;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_Icon;
    private javax.swing.JButton Register_Button;
    private javax.swing.JLabel UserName_Icon;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


}
